# Generated by Django 5.1.3 on 2024-11-29 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('New Service Connection', 'New Service Connection'), ('Service Disconnection', 'Service Disconnection'), ('Billing and Payments', 'Billing and Payments'), ('Meter Issues', 'Meter Issues'), ('Gas Leaks or Safety Concerns', 'Gas Leaks or Safety Concerns'), ('Maintenance Requests', 'Maintenance Requests'), ('Account Updates', 'Account Updates'), ('Reconnection of Service', 'Reconnection of Service'), ('Energy Efficiency Advice', 'Energy Efficiency Advice'), ('Complaints', 'Complaints'), ('General Inquiries', 'General Inquiries'), ('Appointment Scheduling', 'Appointment Scheduling'), ('Moving Services', 'Moving Services'), ('Promotions and Offers', 'Promotions and Offers')], max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_requests.servicerequest')),
            ],
        ),
    ]
